
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <title>Sistemas de Registro de Alumnos </title>
        <meta http-equiv="content-type" content="text/html;charset=utf-8" />
        <meta name="generator" content="Geany 1.27" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" media="all" href="css/fonts7.css"/>
        <link rel="stylesheet" type="text/css" media="all" href="css/screen7.css"/>
        <link rel="stylesheet" type="text/css" media="print" href="css/print7.css"/>
        <link rel="stylesheet" type="text/css" media="screen" href="css/responsive7.css"/>
        <link rel="stylesheet" type="text/css" media="all" href="css/form.css">
        
        <link rel="stylesheet" type="text/css" media="all" href="tablas/jquery.dataTables.min.css">
		<link rel="stylesheet" type="text/css" media="all" href="tablas/dataTables.bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="all" href="css/list2.css">
        
        <script type="text/javascript" src="js/form7.js"></script>
        
		<script type="text/javascript" src="tablas/jquery-1.12.3.js"></script>
		<script type="text/javascript" src="tablas/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="tablas/dataTables.bootstrap.min.js"></script>
<script>
$(document).ready(function (){
	//boton alumno y genera listado alumno
	$(document).on('click', "[id^=alumnos_]",function (e){
		var dato = this.childNodes[0].innerHTML;
		$("#txtIdAlumno").val(dato);
		$('#reponseAlumno').hide();
	});
	$(document).on('click', "#btAlumno",function(r){
		$.ajax({
			data: {
				modo: 's',
				fuera: 's'
			},
			url: 'tablas/alumnos2.phtml',
			type: 'post',
			beforeSend: function () {
				$("#reponseAlumno").html("Procesando, espere por favor ...");
			},
			success: function (response) {
				$("#reponseAlumno").show();
				$("#reponseAlumno").html(response);
			},
		});
	});
	//boton Representante y genera listado representante
	$(document).on('click', "[id^=representantes_]",function (e){
		var dato = this.childNodes[0].innerHTML;
		$("#txtRepresentante").val(dato);
		$('#reponseRepresentante').hide();
	});
	$(document).on('click', "#btRepresentante",function(r){
		$.ajax({
			data: {
				modo: 's',
				fuera: 's'
			},
			url: 'tablas/representantes.phtml',
			type: 'post',
			beforeSend: function () {
				$("#reponseRepresentante").html("Procesando, espere por favor ...");
			},
			success: function (response) {
				$("#reponseRepresentante").show();
				$("#reponseRepresentante").html(response);
			},
		});
	});
	//boton procedencia y genera listado procedencias
	$(document).on('click', "[id^=procedencias_]",function (e){
		var dato = this.childNodes[0].innerHTML;
		$("#txtProcedencia").val(dato);
		$('#reponseProcedencia').hide();
	});
	$(document).on('click', "#btProcedencia",function(r){
		$.ajax({
			data: {
				modo: 's',
				fuera: 's'
			},
			url: 'tablas/procedencias.phtml',
			type: 'post',
			beforeSend: function () {
				$("#reponseProcedencia").html("Procesando, espere por favor ...");
			},
			success: function (response) {
				$("#reponseProcedencia").show();
				$("#reponseProcedencia").html(response);
			},
		});
	});
	
	//boton vivienda y genera listado viviendas
	$(document).on('click', "[id^=viviendas_]",function (e){
		var dato = this.childNodes[0].innerHTML;
		$("#txtVivienda").val(dato);
		$('#reponseVivienda').hide();
	});
	$(document).on('click', "#btVivienda",function(r){
		$.ajax({
			data: {
				modo: 's',
				fuera: 's'
			},
			url: 'tablas/viviendas.phtml',
			type: 'post',
			beforeSend: function () {
				$("#reponseVivienda").html("Procesando, espere por favor ...");
			},
			success: function (response) {
				$("#reponseVivienda").show();
				$("#reponseVivienda").html(response);
			},
		});
	});	

	//boton datos habitacion y genera listado datos_habitacion
	$(document).on('click', "[id^=datos_habitacion_]",function (e){
		var dato = this.childNodes[0].innerHTML;
		$("#txtDatosHabitacion").val(dato);
		$('#reponseDatosHabitacion').hide();
	});
	$(document).on('click', "#btHabitacion",function(r){
		$.ajax({
			data: {
				modo: 's',
				fuera: 's'
			},
			url: 'tablas/datos_habitacion.phtml',
			type: 'post',
			beforeSend: function () {
				$("#reponseDatosHabitacion").html("Procesando, espere por favor ...");
			},
			success: function (response) {
				$("#reponseDatosHabitacion").show();
				$("#reponseDatosHabitacion").html(response);
			},
		});
	});	
	
	
	});
</script>

    </head>

    <body>
        <script>

		 function BuscarRAl() {
                if (document.getElementById("txtIdAlumno").value === "") {
                    window.alert("Debe escribir alguna Id para buscar");
                } else {
                    url = 'php/manejoprocRegistroAlumno.php?modo=b&txtId=' + document.getElementById("txtIdAlumno").value;
                    window.open(url, '_blank');
                }
            }
            ;

            function ListarRAl() {
                url = 'php/manejoprocRegistroAlumno.php?modo=l';
                window.open(url, '_blank');
            }
            ;
        </script>
        <form method="post" id="FSForm" action="php/manejoprocRegistroAlumno.php?modo=a" enctype="application/x-www-form-urlencoded" onsubmit="return Vromansys.Form.processSubmit(this);">
            <div style="display:none;">
                <input name="locid" value="nel_cas_ruiz/form1" type="hidden">
                    <input name="EParam" value="AT1kKIiyxDzVLs0SuJ0SiaeLTfEDMMCuUSAE7pKjsPclansuDaO2v1whqWN/LAwJ" type="hidden">
                        <input name="ElapsedTime" id="ElapsedTime" value="0" type="hidden">
                            <input name="Referrer" id="Referrer" value="" type="hidden">
                                <input name="subject_line" id="subject_line" autocomplete="off" type="text"><label for="subject_line">subject_line</label>
                                    </div>

                                    <!-- BEGIN_ITEMS -->
		<div class="form_table">
			<div class="clear"></div>

			<div id="q0" class="q full_width">
				<a class="item_anchor" name="ItemAnchor0"></a>
				<div class="segment_header" style="width:auto;text-align:Center;"><h1 style="font-size:24px;padding:20px 1em ;">Procesar Registro Alumno</h1></div>
			</div>

			<div class="clear"></div>

			<div id="q44" class="q">
				<a class="item_anchor" name="ItemAnchor1"></a>
				<label class="question top_question" for="txtIdAlumno">Seleccion de Alumno  <b class="icon_required" style="color:#FF0000"> *</b></label>
				<input name="txtIdAlumno" class="text_field" id="txtIdAlumno" size="15" maxlength="100" type="text" value="">
					<input name="btAlumno" type="button" id="btAlumno" value="Buscar Alumno" /> 
					<div name="reponseAlumno" id="reponseAlumno">

					</div>
			</div>
			<div class="clear"></div>

			<div id="q45" class="q required">
				<a class="item_anchor" name="ItemAnchor2"></a>
				<label class="question top_question" for="txtRepresentante">Seleccion de Representante </label>
				<input name="txtRepresentante" class="text_field" id="txtRepresentante" size="20" maxlength="100"  type="text" >
					<input name="btRepresentante" id="btRepresentante" type="button" value="Buscar Representante" /> 
					<div name="reponseRepresentante" id="reponseRepresentante">

					</div>
			</div>
			<div class="clear"></div>

			<div id="q46" class="q required">
				<a class="item_anchor" name="ItemAnchor3"></a>
				<label class="question top_question" for="txtProcedencia">Seleccion de Procedencia  </label>
				<input name="txtProcedencia" class="text_field" id="txtProcedencia" size="20" maxlength="100" type="text">
					<input name="btProcedencia" type="button"  id="btProcedencia"  value="Buscar Procedencia" /> 
					<div name="reponseProcedencia" id="reponseProcedencia" >

					</div>
			</div>
			<div class="clear"></div>

			<div id="q47" class="q required">
				<a class="item_anchor" name="ItemAnchor4"></a>
				<label class="question top_question" for="txtVivienda">Seleccion de Vivienda </label>
				<input name="txtVivienda" class="text_field" id="txtVivienda" size="20" maxlength="100" type="text">
					<input name="btVivienda" type="button" id="btVivienda" value="Buscar Vivienda" /> 
					<div name="reponseVivienda" id="reponseVivienda">

					</div>
			</div>
			<div class="clear"></div>

			<div id="q4" class="q required">
				<a class="item_anchor" name="ItemAnchor3"></a>
				<label class="question top_question" for="txtDatosHabitacion">Seleccion de Datos de Habitacion </label>
				<input name="txtDatosHabitacion" class="text_field" id="txtDatosHabitacion" size="20" maxlength="100" type="text">
					<input name="btHabitacion" type="button" id="btHabitacion"  value="Buscar Habitacion" /> 
					<div name="reponseDatosHabitacion" id="reponseDatosHabitacion" >

					</div>
			</div>
		</div>

                                    <!-- END_ITEMS -->
                                    <input name="EParam" value="FzpUCZwnDno=" type="hidden">
                                        <div class="outside_container">
                                            <div class="buttons_reverse">
                                                <input name="Guardar" value="Guardar" class="submit_button" id="FSsubmit" type="submit">
                                                    <input name="Buscar" value="Buscar" class="submit_button" id="Buscar" type="button" onclick="BuscarRAl()">
                                                        <input name="Listar" value="Listar" class="submit_button" id="Listar" type="button" onclick="ListarRAl();">
                                                            </div></div>
                                                            </form>
        <script>                                                    
 		$(document).ready(function() {
		$('#tabla_alumnos').DataTable();
		} );
		</script>
</body>

</html>
