<?php 
// aqui se contuyen los encabezados de la tabla
include_once ("../php/conexion.php");
$tabla='alumnos';
//$this->tabla= $tabla;
$con= new Conector_pg('127.0.0.1', 'UELibertador', 'junior', 'junior');

  	$encabezado='<thead>';
	$encabezado.='<tr  BGCOLOR="#58ACFA">';	
	$pie='<tfoot>';
	$pie.='<tr  BGCOLOR="#58ACFA">';	
	$encabezado.= '<th>Id</th>
                <th>Apellidos</th>
                <th>Nombres</th>
                <th>Sexo</th>
                <th>Ciescolar</th>';
	$encabezado .= 	'</tr> </thead>';
	$pie.= '<th>Id</th>
                <th>Apellidos</th>
                <th>Nombres</th>
                <th>Sexo</th>
                <th>Ciescolar</th>';
	$pie .= 	'</tr> </tfoot>';
  
$cadena= "SELECT id, apellidos, nombres, sexo, ciescolar FROM ".$tabla." ORDER BY id";

//si tiene indice deberia ordenarse
//unset($resultadoc);
$resultarow = $con->consultar($cadena); 
$cont=0;
$strout2='';
//print_r($resultarow);
if ($resultarow) { 
	$recordcount=$con->contar($resultarow);
	}else{
		$recordcount=0;
		exit(); 
		}
	//echo $recordcount;
    $id='1';
    $datarec = '';
	while ($row = pg_fetch_assoc($resultarow))
	{		
		$datarec.='<tr>';
		$datarec .= "<td>".$row['id']."</td>";
		$datarec .= "<td>".$row['apellidos']."</td>";
		$datarec .= "<td>".$row['nombres']."</td>";
		$datarec .= "<td>".$row['sexo']."</td>";
		$datarec .= "<td>".$row['ciescolar']."</td>";
		$datarec.='</tr>';
	 }
// aqui se contuyen los encabezados de la tabla
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head>
<meta charset="utf-8">
<title>Prueba tablas de datos ALUMNOS </title>
<link rel="stylesheet" type="text/css" media="all" href="jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" media="all" href="dataTables.bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="all" href="../css/list2.css">


<script type="text/javascript" src="jquery-1.12.3.js"></script>
<script type="text/javascript" src="jquery.dataTables.min.js"></script>
<script type="text/javascript" src="dataTables.bootstrap.min.js"></script>

<link rel="stylesheet" type="text/css" media="all" href="buttons.dataTables.min.css">
    	    
<script type="text/javascript" src="js/form7.js"></script>

<script type="text/javascript" src="dataTables.buttons.min.js"></script>
<script type="text/javascript" src="buttons.flash.min.js"></script>
<script type="text/javascript" src="jszip.min.js"></script>
<script type="text/javascript" src="pdfmake.min.js"></script>
<script type="text/javascript" src="vfs_fonts.js"></script>
<script type="text/javascript" src="buttons.html5.min.js"></script>
<script type="text/javascript" src="buttons.print.min.js"></script>
		
</head>
<body>
<table id="tabla" class="dataTable" cellspacing="0" width="100%">
<?php 
echo $encabezado;
echo $pie;
?>
    <tbody class="cebra">
<?php 			
echo $datarec;
?>	 
        </tbody>
    </table>
<script>
$(document).ready(function() {
    $('#tabla').DataTable( {
        dom: 'Bfrtip',
        buttons: [
             'excel', 'pdf', 'print'
        ]
    } );
} );
		
</script>
</body>

