<?php 
// aqui se contuyen los encabezados de la tabla
include_once ("../php/conexion.php");
$tabla='cumple';
//$this->tabla= $tabla;
$con= new Conector_pg('127.0.0.1', 'UELibertador', 'junior', 'junior');
$cadena="SELECT  distinct (a.attname) as column_name, t.typname as data_type, e.ordinal_position as orden,
CASE
WHEN cc.contype= 'p' THEN 'PRI'
WHEN cc.contype= 'u' THEN 'UNI'
WHEN cc.contype= 'f' THEN 'FK'
ELSE '' END AS key,
CASE WHEN a.attnotnull=false THEN 'YES' ELSE 'NO' END AS is_nullable,
CASE WHEN a.attlen= '-1' THEN (a.atttypmod  - 4) ELSE a.attlen END as max_length,
d.adsrc as column_default
FROM pg_catalog.pg_attribute a
LEFT JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
LEFT JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
LEFT JOIN pg_catalog.pg_constraint cc ON cc.conrelid = c.oid AND cc.conkey[1] = a.attnum
LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = c.oid AND a.attnum = d.adnum
LEFT JOIN information_schema.columns e on e.column_name= a.attname AND e.table_name = '".$tabla."'
WHERE c.relname = '".$tabla."' AND a.attnum > 0 AND t.oid = a.atttypid ORDER BY orden;";
$resultadoc = $con->consultar($cadena); 
$cont=0;
if ($resultadoc) { 
	$cont=$con->contar($resultadoc);
	}else{
		$cont =' - sin registros - '; 	
	}
  
	$encabezado='<thead>';
	$encabezado.='<tr  BGCOLOR="#58ACFA">';	
	$pie='<tfoot>';
	$pie.='<tr  BGCOLOR="#58ACFA">';	
		while($col=$con->registros($resultadoc))
		{
				$encabezado.= '<th>'.ucwords($col->column_name).'</th>';
				$pie.= '<th>'.ucwords($col->column_name).'</th>';
				$arr[] = $col->column_name;
				if($col->key=='PRI') $indice = $col->column_name;
		}
		$encabezado .= 	'</tr> </thead>';
		$pie .= 	'</tr> </tfoot>';
  // echo $encabezado;
$cadena= "SELECT * FROM ".$tabla." ; ";

//si tiene indice deberia ordenarse
unset($resultadoc);
$resultarow = $con->consultar($cadena); 
$cont=0;
$strout2='';
//print_r($resultarow);
if ($resultarow) { 
	$recordcount=$con->contar($resultarow);
	}else{
		$recordcount=0;
		exit(); 
		}
	//echo $recordcount;
    $id='1';
    $datarec = '';
	while ($row = pg_fetch_assoc($resultarow))
	{		
		//print_r($arr);
		$datarec.='<tr>';
		foreach ($arr as $rec) {
//		$datarec.= '<td>'.$row[$rec].'</td>';
			$datarec .= "<td>".$row[$rec]."</td>";
			//echo $misdatos;
		 }
		 
		 //$datarec.='<td>'.$row[$rec].'</td>';
		$datarec.='</tr>';
	 }
// aqui se contuyen los encabezados de la tabla
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head>
<meta charset="utf-8">
<title>Prueba tablas de datos</title>
<link rel="stylesheet" type="text/css" media="all" href="jquery.dataTables.css">
<link rel="stylesheet" type="text/css" media="all" href="dataTables.bootstrap.min.css">

<script type="text/javascript" src="jquery-1.12.3.js"></script>
<script type="text/javascript" src="jquery.dataTables.min.js"></script>
<script type="text/javascript" src="dataTables.bootstrap.min.js"></script>

</head>
<body>
<table id="tabla_cumple" class="dataTable" cellspacing="0" width="100%">
<?php 
echo $encabezado;
echo $pie;
?>
        <tbody>
<?php 			
echo $datarec;
?>	 
        </tbody>
    </table>
<script>
	$(document).ready(function() {
    var table = $('#tabla_cumple').DataTable({
        "columnDefs": [
            { "visible": false, "targets": 5 }
        ],
        "order": [[ 5, 'asc' ]],
        "displayLength": 25,
        "drawCallback": function ( settings ) {
            var api = this.api();
            var rows = api.rows( {page:'current'} ).nodes();
            var last=null;
 
            api.column(5, {page:'current'} ).data().each( function ( group, i ) {
                if ( last !== group ) {
                    $(rows).eq( i ).before(
                        '<tr class="group"><td colspan="5">'+group+'</td></tr>'
                    );
 
                    last = group;
                }
            } );
        }
    } );
 
    // Order by the grouping
    $('#tabla_cumple tbody').on( 'click', 'tr.group', function () {
        var currentOrder = table.order()[0];
        if ( currentOrder[0] === 2 && currentOrder[1] === 'asc' ) {
            table.order( [ 5, 'desc' ] ).draw();
        }
        else {
            table.order( [ 5, 'asc' ] ).draw();
        }
    } );
} );
</script>
</body>

