<?php 
// aqui se contuyen los encabezados de la tabla
include_once ("../php/conexion.php");
$tabla='cumple';
//$this->tabla= $tabla;
$con= new Conector_pg('127.0.0.1', 'UELibertador', 'junior', 'junior');
$cadena="SELECT  distinct (a.attname) as column_name, t.typname as data_type, e.ordinal_position as orden,
CASE
WHEN cc.contype= 'p' THEN 'PRI'
WHEN cc.contype= 'u' THEN 'UNI'
WHEN cc.contype= 'f' THEN 'FK'
ELSE '' END AS key,
CASE WHEN a.attnotnull=false THEN 'YES' ELSE 'NO' END AS is_nullable,
CASE WHEN a.attlen= '-1' THEN (a.atttypmod  - 4) ELSE a.attlen END as max_length,
d.adsrc as column_default
FROM pg_catalog.pg_attribute a
LEFT JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
LEFT JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
LEFT JOIN pg_catalog.pg_constraint cc ON cc.conrelid = c.oid AND cc.conkey[1] = a.attnum
LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = c.oid AND a.attnum = d.adnum
LEFT JOIN information_schema.columns e on e.column_name= a.attname AND e.table_name = '".$tabla."'
WHERE c.relname = '".$tabla."' AND a.attnum > 0 AND t.oid = a.atttypid ORDER BY orden;";
$resultadoc = $con->consultar($cadena); 
$cont=0;
if ($resultadoc) { 
	$cont=$con->contar($resultadoc);
	}else{
		$cont =' - sin registros - '; 	
	}
  
	$encabezado='<thead>';
	$encabezado.='<tr  BGCOLOR="#58ACFA">';	
	$pie='<tfoot>';
	$pie.='<tr  BGCOLOR="#58ACFA">';	
		while($col=$con->registros($resultadoc))
		{
				$encabezado.= '<th>'.ucwords($col->column_name).'</th>';
				$pie.= '<th>'.ucwords($col->column_name).'</th>';
				$arr[] = $col->column_name;
				if($col->key=='PRI') $indice = $col->column_name;
		}
		$encabezado .= 	'</tr> </thead>';
		$pie .= 	'</tr> </tfoot>';
  // echo $encabezado;
$cadena= "SELECT * FROM ".$tabla." ORDER BY CASE 'mes'
    WHEN 'Enero' THEN 1
    WHEN 'Febrero' THEN 2
    WHEN 'Marzo' THEN 3
    WHEN 'Abril' THEN 4
    WHEN 'Mayo' THEN 5
    WHEN 'Junio' THEN 6
    WHEN 'Julio' THEN 7
    WHEN 'Agosto' THEN 8
    WHEN 'Septiembre' THEN 9
    WHEN 'Octubre' THEN 10
    WHEN 'Noviembre' THEN 11
    WHEN 'Diciembre' THEN 12
    ELSE 0
END , dia; ";

//si tiene indice deberia ordenarse
unset($resultadoc);
$resultarow = $con->consultar($cadena); 
$cont=0;
$strout2='';
//print_r($resultarow);
if ($resultarow) { 
	$recordcount=$con->contar($resultarow);
	}else{
		$recordcount=0;
		exit(); 
		}
	//echo $recordcount;
    $id='1';
    $datarec = '';
	while ($row = pg_fetch_assoc($resultarow))
	{		
		$datarec.='<tr>';
		foreach ($arr as $rec) {
			$datarec .= "<td>".$row[$rec]."</td>";
		 }
		$datarec.='</tr>';
	 }
// aqui se contuyen los encabezados de la tabla
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
	<title>Listado de Cumpleaños</title>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" media="all" href="jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" media="all" href="dataTables.bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="all" href="../css/list2.css">


<script type="text/javascript" src="jquery-1.12.3.js"></script>
<script type="text/javascript" src="jquery.dataTables.min.js"></script>
<script type="text/javascript" src="dataTables.bootstrap.min.js"></script>

<link rel="stylesheet" type="text/css" media="all" href="buttons.dataTables.min.css">
    	    
<script type="text/javascript" src="js/form7.js"></script>

<script type="text/javascript" src="dataTables.buttons.min.js"></script>
<script type="text/javascript" src="buttons.flash.min.js"></script>
<script type="text/javascript" src="jszip.min.js"></script>
<script type="text/javascript" src="pdfmake.min.js"></script>
<script type="text/javascript" src="vfs_fonts.js"></script>
<script type="text/javascript" src="buttons.html5.min.js"></script>
<script type="text/javascript" src="buttons.print.min.js"></script>
</head>
<body>
<table id="tabla_cumple" class="dataTable" cellspacing="0" width="100%">
<?php 
echo $encabezado;
echo $pie;
?>
        <tbody>
<?php 			
echo $datarec;
?>	 
        </tbody>
    </table>
<script>

	$(document).ready(function() {
    $('#tabla_cumple').DataTable( {
		dom: 'Bfrtip',
        buttons: [
            'excel', 'pdf', 'print'
        ],
        
        "columnDefs": [
            { "visible": false, "targets": 5 }
        ],
        "order": [[ 5, 'asc' ]],
        "displayLength": 10,
        "drawCallback": function ( settings ) {
            var api = this.api();
            var rows = api.rows( {page:'current'} ).nodes();
            var last=null;
 
            api.column(5, {page:'current'} ).data().each( function ( group, i ) {
                if ( last !== group ) {
                    $(rows).eq( i ).before(
                        '<tr class="group"><td colspan="5">'+group+'</td></tr>'
                    );
 
                    last = group;
                }
            } );
        }
    
    } );
} );

</script>
</body>

