<?php 
// aqui se contuyen los encabezados de la tabla
include_once ("../php/conexion.php");
$tabla='constancia_inscripcion_view';
$con= new Conector_pg('127.0.0.1', 'UELibertador', 'junior', 'junior');

  	$encabezado='<thead>';
	$encabezado.='<tr  BGCOLOR="#58ACFA">';	
	$pie='<tfoot>';
	$pie.='<tr  BGCOLOR="#58ACFA">';	
	$encabezado.= '<th>IdAlumno</th>
				<th>Ciescolar</th>
                <th>Apellidos</th>
                <th>Nombres</th>';
	$encabezado .= 	'</tr> </thead>';
	$pie.= '<th>IdAlumno</th>
				<th>Ciescolar</th>
                <th>Apellidos</th>
                <th>Nombres</th>';
	$pie .= 	'</tr> </tfoot>';

$idgrupo = $_REQUEST['idgrupo'];

$cadena= "Select * from $tabla where
idgrupo='$idgrupo' ";

//si tiene indice deberia ordenarse
//unset($resultadoc);
$resultarow = $con->consultar($cadena); 
$cont=0;
$strout2='';
//print_r($resultarow);
if ($resultarow) { 
	$recordcount=$con->contar($resultarow);
	}else{
		$recordcount=0;
		exit(); 
		}
	//echo $recordcount;
    $id='1';
    $datarec = '';
	while ($row = pg_fetch_assoc($resultarow))
	{		
		$datarec.="<tr id='alumnos_".$row['ciescolar']."'>";
			$datarec .= "<td>".$row['idalumno']."</td>";
			$datarec .= "<td>".$row['ciescolar']."</td>";
			$datarec .= "<td>".$row['apellidos']."</td>";
			$datarec .= "<td>".$row['nombres']."</td>";
		$datarec.='</tr>';
	 }
// aqui se contuyen los encabezados de la tabla
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head>
<meta charset="utf-8">
</head>
<body>

<table id="tabla_alumnos" class="dataTable" cellspacing="0" width="100%">
<?php 
echo $encabezado;
echo $pie;
?>
    <tbody class="cebra">
<?php 			
echo $datarec;
?>	 
        </tbody>
    </table>
<script>
	$(document).ready(function() {
		$('#tabla_alumnos').DataTable();
	} );
</script>

